import { Button } from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
	return (
		<>
			<Head>
				<title>Spanish Conjugation</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Link href="/session">
				<Button colorScheme="blue">Start a Session</Button>
			</Link>
		</>
	);
}
